branches:
  only:
    - "project-hiroshima"

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - FLASK=0.10.1
matrix:
  allow_failures:
    - python: "2.6"
    - python: "2.7"
    - env: FLASK=dev

install:
  - pip install flask==$FLASK --use-mirrors
  - pip install git+git://github.com/mitsuhiko/flask-sqlalchemy.git
  - pip install flask-babel --use-mirrors
  - pip install git+git://github.com/FSX/flask-seasurf.git
  - pip install sqlalchemy --use-mirrors

  - hg clone https://bitbucket.org/babel3_developers/babel3
  - cd babel3
  - mkdir babel/localedata
  - wget http://unicode.org/Public/cldr/1.7.2/core.zip
  - unzip core.zip
  - python setup.py egg_info
  - python scripts/import_cldr.py common/
  - python setup.py install
  - cd ..
script:
  - python tests.py
