branches:
  only:
    - "project-hiroshima"

language: python
python:
  - "3.3"
env:
  - FLASK=0.10.1
matrix:
  allow_failures:
    - env: FLASK=dev

install:
  - pip install flask==$FLASK --use-mirrors
  - pip install git+git://github.com/mitsuhiko/flask-sqlalchemy.git
  - pip install flask-babelex --use-mirrors
  - pip install flask-seasurf
  - pip install markdown --use-mirrors

  # Babel3 requires complex installation procedure - don't ask why... please.
  - hg clone https://bitbucket.org/babel3_developers/babel3
  - cd babel3
  - mkdir babel/localedata
  - wget http://unicode.org/Public/cldr/1.7.2/core.zip
  - unzip core.zip
  - python setup.py egg_info
  - python scripts/import_cldr.py common/
  - python setup.py install
  - cd ..

  # Create settings.cfg file from settings.cfg.sample with correct path to
  # blueprints directory with sed magic.
  - "sed \"s:^BLUEPRINTS_DIRECTORY.*$:BLUEPRINTS_DIRECTORY = '$(pwd)\\/freevle\\/blueprints\\/':\" <settings.cfg.sample >settings.cfg"
script:
  - python test.py ../settings.cfg
